### ISSUE TITLE
Adapter can't handle ObjectID

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune-mongodb#11]
When using the following option for generateId:
```
generateId: function(){
    return new mongodb.ObjectID().str;
}
```
Fortune will correctly save records with an ObjectID. When it tries to find the records the result is always empty. It most likely tries to do it with a string or hex representation of the ObjectId which results in 0 records which needs to be cast to an ObjectID before being sent to MongoDB.

Applicable error message from fortune: 
`A related record for the field "person" was not found.`
With the test case of saving an item with an added relationship to the person.

**Comment by 0x8890** [comment]
Internally it doesn't work because ObjectIds do not work with the equality operator, i.e. `ObjectId('foo') === ObjectId('foo')`. Because of this, the primary key must be a unique primitive type (string, number, or symbol if you're daring but i haven't tested this). it says in the docs here: http://fortunejs.com/api/#adapter

According to the MongoDB documentation the only benefits that you get from using ObjectId:

>in the mongo shell, you can access the creation time of the ObjectId, using the getTimestamp() method.
>sorting on an _id field that stores ObjectId values is roughly equivalent to sorting by creation time.

Even if you wanted to store a timestamp as part of the ID, you can implement the `generatePrimaryKey` option. Closing for now, unless there is a compelling use case for using ObjectId.

**Comment by nickschot** [comment]
I was mainly looking for a good alternative to the default base64 encoded ID's because they're not URL safe. I wrote a serializer for Ember to url encode/decode the ID's when they enter/leave via the JSON API adapter. Yet, this still gives problems as it seems the ID's are internally URL encoded a second time which invalidates the ID for usage in requests to fortune (eg /items/:double_encoded_ID).

**Comment by 0x8890** [comment]
hmm, the tests run just fine with the default base64 ids, it's just necessary to make sure you're properly encoding URIs.

the default behavior may be overridden, so for example to generate hexademical ids:

```js
options: {
  generatePrimaryKey () {
    return crypto.randomBytes(16).toString('hex')
  }
}
```

I think that would solve your problem.

**Comment by nickschot** [comment]
Yea the "problem" I'm having is not in Fortune itself but the combination of ember, fortune and non-URL safe ID's. I'll try it out!
